version: "3.7"
services:
  app:
    image: ghcr.io/zisoo-choi/kdt1-study-3-team1-fastapi:latest
    container_name: docker-fastapi-deploy-server
    ports:
      - 8000:8000
    networks:
      - app

networks:
  app:
    driver: bridge